### ISSUE TITLE
Support for . values 

### ISSUE THREAD

**Issue by pstawinski** [lifeomic/spark-vcf#6]
Hi,

thank you for a great tool. Could you please consider supporting a numeric value ".", which in VCF means (AFAIK): no value (null maybe)?

For example UnifiedGenotyper (GATK) after declaring a field:

`##INFO=<ID=RPA,Number=.,Type=Integer,Description="Number of times tandem repeat unit is repeated, for each allele (including reference)">
`
can sometimes put:

`UG_RPA=.`

info field.
Thank you,
Piotr

**Comment by pstawinski** [comment]
I'm sorry, seems to be solved in 2.1 version (I was using 1.0).
Thanks, best wishes,
Piotr

**Comment by dmmiller612** [comment]
No problem. Yep, I believe this should be addressed in version 0.2.1.
